# Show me more numpy!

## Review!

How do I see the number of dimensions and number of elements in a numpy array?


In [1]:
import numpy as np

nparray = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
print("nparray\n", nparray)

# number of dimensions
print(nparray.ndim)

# number of elements
print(nparray.size)

# overall shape
print(nparray.shape)


nparray
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
12
(3, 4)


In [3]:
shape = nparray.shape
shape[1]

4

## Getting into numpy arrays

Indexing into vectors

In [4]:
v = np.array([1, 2, 3])

# what if i want the second item in v
print(v[1])

2


Indexing into matrices

In [5]:
m = np.array([[1,2,3], [4,5,6]])

#  what if I want the first row second column item in m
print(m[0][1])

2


In [6]:
# what happens if I do this?
print(m[1]) 

[4 5 6]


In [7]:
# what happens if I do this?
print(m[:, 1])

[2 5]


* these are *slices* of arrays
* a slice of a matrix is a vector
* a slice of a tensor is a matrix or another tensor

Indexing into tensors

In [8]:
t = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]],  [[17,18,19,20], [21,22,23,24]]])

# let's remind ourselves what t looks like
print(t)
print(t.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
(3, 2, 4)


In [9]:
# what if I want the first array 2nd row 3rd column item in t?
print(t[0][1][2])

7


In [10]:
# what is the slice of t indexed like this?
print(t[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [11]:
# what about like this?
print(t[:,1])

[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]]


In [12]:
# what about like this?
print(t[:,:,1])

[[ 2  6]
 [10 14]
 [18 22]]


Now you do it!

In [13]:
nparray = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]])
print("nparray\n", nparray)

nparray
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [14]:
# (review!) how do I access the element in the top left corner of nparray?
print(nparray[0][0])

0


In [15]:
# is there a prettier way?
print(nparray[0, 0])

# this is only marginally prettier for a 2-d array but imagine a 10-d array!

0


In [16]:
# how do I access the whole first column?
print(nparray[:, 0])

[ 0 10 20 30]


In [17]:
# what about the whole second row?
print(nparray[2, :])

[20 21 22 23]


In [18]:

# what about the last two rows?
print(nparray[-2:, :])
print(nparray[1:, :]) #this also works



[[20 21 22 23]
 [30 31 32 33]]
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [19]:
# what about the first row and last two columns?
print("first row, last two columns")
print(nparray[0, 2:])

first row, last two columns
[2 3]


In [20]:
# how do I access the 1st and 3rd columns?
print("first and third columns")
print(nparray[:, [1, 3]])

first and third columns
[[ 1  3]
 [11 13]
 [21 23]
 [31 33]]


In [21]:
# let's do it another way
print(nparray[np.ix_(np.arange(nparray.shape[0]), [1, 3])])

# what is np.ix_??
# The function takes N 1-D sequences and returns N outputs with N dimensions each

[[ 1  3]
 [11 13]
 [21 23]
 [31 33]]


## Modifying (slices of) arrays

In [22]:
# how do I *change* the element at 1, 1 of the array?
nparray[1,1] = 101
print(nparray)

[[  0   1   2   3]
 [ 10 101  12  13]
 [ 20  21  22  23]
 [ 30  31  32  33]]


In [23]:
# and now for some magic! how do I assign the second row to 1s?
nparray[1] = 1
print(nparray)
print(nparray.dtype)

[[ 0  1  2  3]
 [ 1  1  1  1]
 [20 21 22 23]
 [30 31 32 33]]
int64


In [24]:
# how do I assign the second row to increasing ints?
nparray[1] = np.arange(nparray.shape[1])
print(nparray)
print(nparray.dtype)

[[ 0  1  2  3]
 [ 0  1  2  3]
 [20 21 22 23]
 [30 31 32 33]]
int64


In [26]:
# how do I assign the second row to 3* itself?
nparray[1] *= 3
print(nparray)


[[ 0  1  2  3]
 [ 0  9 18 27]
 [20 21 22 23]
 [30 31 32 33]]
